### ISSUE TITLE
Basic deserailizing type checking

### ISSUE THREAD

**Issue by LPardue** [undef1nd/sfv#76]
I feel pretty dumb asking this.

So I want to use the crate to help me handle [Extensible Priorities headers](https://tools.ietf.org/html/draft-ietf-httpbis-priority-01), which is a set of priority parameters encoded as a Structured Headers Dictionary. 

So far we have defined two parameters, `u` is an sh-integer, and `i` is a sh-boolean. When I parse this I want to ensure that the parameters are the expected type. 

Take this example

```
fn main() {
    let ext_priority = "u=2,i";
    let dict = Parser::parse_dictionary(ext_priority.as_bytes());
    assert!(dict.is_ok());
    println!("{:#?}", dict);
}

prints:

Ok(
    {
        "u": Item(
            Item {
                bare_item: Integer(
                    2,
                ),
                params: {},
            },
        ),
        "i": Item(
            Item {
                bare_item: Boolean(
                    true,
                ),
                params: {},
            },
        ),
    },
)

```
great, it works!

But if I modify the input slightly to change the contents of `u`

```
fn main() {
    let ext_priority = "u=ohnoibrokeit,i";
    let dict = Parser::parse_dictionary(ext_priority.as_bytes());
    assert!(dict.is_ok());
    println!("{:#?}", dict);
}

prints:

Ok(
    {
        "u": Item(
            Item {
                bare_item: Token(
                    "ohnoibrokeit",
                ),
                params: {},
            },
        ),
        "i": Item(
            Item {
                bare_item: Boolean(
                    true,
                ),
                params: {},
            },
        ),
    },
)
```

The parser reads this as sh-token, not sh-integer. 

How can I do some basic type checking of the parsing result?

**Comment by LPardue** [comment]
Ok, hunting through the code and tweaking things slightly gives me a snippet that seems to achieve what I want

```
  if let Some(ListEntry::Item(item)) = dict.get("u") {
        let item_value = item
            .bare_item
            .as_int()
            .ok_or("unexpected BareItem variant").unwrap();
        assert_eq!(item_value, 2);
    }
```

I wonder if there is a way to do this with some more syntactic sugar, how do other libraries approach it.

**Comment by LPardue** [comment]
I guess this can be reduced down to 

```
let urgency = match dict.get("u") {
        Some(ListEntry::Item(item)) => item.bare_item.as_int(),
        _ => None
    };
``` 

which would probably work for me.

**Comment by undef1nd** [comment]
Hello @LPardue 
Thanks for checking this crate.
Your question is a good one. I agree, that it's too verbose and getting value requires many levels of matching. Hopefully, I'll find a way to make the api better. 

For the time being I unwrap values like this, pretty similar to your snippet:
```rust
use sfv::*;

fn main() {
    let ext_priority = "u=2,i";
    let dict = Parser::parse_dictionary(ext_priority.as_bytes()).unwrap();


    if let Some(ListEntry::Item(item)) = dict.get("u") {
        match item.bare_item {
            BareItem::Integer(val) => { println!("{}", val);}
            _ => ()
        }
    }
}
```

**Comment by undef1nd** [comment]
> I guess this can be reduced down to
> 
> ```
> let urgency = match dict.get("u") {
>         Some(ListEntry::Item(item)) => item.bare_item.as_int(),
>         _ => None
>     };
> ```
> 
> which would probably work for me.

I think you'll still need either to match on `urgency` to get value returned by `as_int()`, or just call `urgency.is_some()` to make sure it's indeed sh-integer.
```rust
use sfv::*;

fn main() {
    let ext_priority = "u=2,i";
    let dict = Parser::parse_dictionary(ext_priority.as_bytes()).unwrap();

    let urgency = match dict.get("u") {
        Some(ListEntry::Item(item)) => item.bare_item.as_int(),
        _ => None,
    };
    
    if let Some(val) = urgency {
        // do something with val
        println!("{}", val);
    }
}
```

**Comment by LPardue** [comment]
Yeah I left that off my snippet thanks. 

My intent was to collapse down the two matches into a single Option but I wonder if that is actually the right thing to do in this case, let me explain.

In extensible priorities, omitting a parameter implies a default value. So if we received a header without "u", we should assume the default value 3. This needs to be done in my code not your parser code. 

I'm not exactly sure how to handle the case whe  "u" is present but not a valid sh-integer. I can assume a default, or reject a request, or maybe something else.

**Comment by undef1nd** [comment]
yeah, looks like you still need separate branches - one to handle missing `u` in dict, and the other one if `u`'s value is not int. 
Maybe if you need to fallback to default value if `u` is missing, this will be a bit more concise?

```rust
const DEFAULT: i64 = 3;
let dict = Parser::parse_dictionary(ext_priority.as_bytes()).unwrap();
let priority = {
        if let Some(ListEntry::Item(item)) = dict.get("u") {
            item.bare_item.as_int().unwrap_or(DEFAULT) // if u is not sh-integer
        } else {
            DEFAULT // if u is missing
        }
    };
```

**Comment by LPardue** [comment]
I'm closing this issue as we found a good solution to my problem and you have a new issue for the documentation thingie. Thanks again.
