### ISSUE TITLE
Update documentation to refer to RFC 8941

### ISSUE THREAD

**Issue by pyfisch** [undef1nd/sfv#83]
The old link <https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html> doesn't work anymore, so it should be updated to <https://www.rfc-editor.org/rfc/rfc8941.html> and text should no longer say "IETF draft"

* [x] About text on Github
* [x] Cargo.toml
* [x] README.md
* [x] lib.rs docstring

I can update the source code.

**Comment by undef1nd** [comment]
Thanks a lot for filing an issue!
I'd be grateful if you could do it @pyfisch

**Comment by undef1nd** [comment]
Closed with #85 
Thanks @pyfisch once again.
