### ISSUE TITLE
Confused about license

### ISSUE THREAD

**Issue by pyfisch** [undef1nd/sfv#84]
[The LICENSE file](https://github.com/undef1nd/sfv/blob/master/LICENSE) contains the Mozilla Public License 2.0 while in [Cargo.toml](https://github.com/undef1nd/sfv/blob/master/Cargo.toml) the license is given as "MIT/Apache-2.0". 

Guide for `license` field: https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=license#the-license-and-license-file-fields I assume MPL was the intended license, then `MPL-2.0` is the correct value for this field.

**Comment by undef1nd** [comment]
Good catch!

Gonna change it to MIT.

**Comment by pyfisch** [comment]
Any reason for not dual-licensing under Apache-2.0? It is the preferred combination in the Rust ecosystem and many/most crates use it. 

* https://github.com/dtolnay/rust-faq#why-a-dual-mitasl2-license
* https://rust-lang.github.io/api-guidelines/necessities.html

I am not a lawyer and can't really comment on the differences between these licenses.

**Comment by undef1nd** [comment]
Same.

MIT looks like a more permissive https://choosealicense.com/licenses/ one. So yeah, I can do a dual license MIT/Apache
